set-option -g base-index 1
set-option -g clock-mode-style 24
set-option -sg escape-time 1
set-option -g prefix C-q
set-option -g key-mode vi
set-option -g detach-on-destroy off
set-option -ga terminal-overrides ",xterm-256color:Tc"

run-shell ${pkgs.tmuxPlugins.catppuccin}/share/tmux-plugins/catppuccin/catppuccin.tmux
set -g @catppuccin_window_status_style basic
set -g @catppuccin_status_default on
set -g @catppuccin_window_default_fill number
set -g @catppuccin_window_current_fill number
set -g @catppuccin_window_default_text " #W  #{window_panes}#{?window_zoomed_flag,   ,}"
set -g @catppuccin_window_current_text " #W  #{window_panes}#{?window_zoomed_flag,   ,}"
set -g @catppuccin_status_fill icon
set -g @catppuccin_status_connect_separator yes
set -g @catppuccin_status_left_separator █
set -g @catppuccin_status_right_separator █
set -g @catppuccin_application_icon "󰜎  "
set -g @catppuccin_session_icon "  "
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set -g status-left ""

bind-key \` display-popup
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R
bind -r W select-pane -t .+1 \; resize-pane -Z
