#!/usr/bin/env bash

if [[ ! -e "$PWD/flake.nix" ]]; then
    echo "[error] no flake.nix found in '$PWD/flake.nix'" >&2
    exit 1
fi

if command -v nix-pkgvercmp &> /dev/null; then
    if ! nix-pkgvercmp; then
        if command -v nix-sync-lock-from-nixos &> /dev/null; then
            read -rp "[warn] nix revision versions are mismatched. sync now? [y/*]: " answer
            if [[ "$answer" == "y" ]]; then
                nix-sync-lock-from-nixos || exit 1
            else
                read -rp "[warn] continue without syncing? [y/*]: " answer
                [[ "$answer" != "y" ]] && exit 1
            fi
        else
            read -rp "[warn] nix revision versions are mismatched. continue? [y/*]: " answer
            [[ "$answer" != "y" ]] && exit 1
        fi
    fi
else
    read -rp "[warn] 'nix-pkgvercmp' is not available. continue? [y/*]: " answer
    [[ "$answer" != "y" ]] && exit 1
fi

exec nix develop "$@"
