#!/usr/bin/env bash

if ! command -v "tmux" &> /dev/null; then
    echo "[error] no tmux" >&2
    exit 1
fi

if [ -z "${1:-}" ]; then
    echo "[error] missing directory. Usage: $0 <directory>" >&2
    exit 1
fi

SESSION_DIR=$(realpath "$1")
if [ ! -d "$SESSION_DIR" ]; then
    echo "[error] invalid directory. Not found: $SESSION_DIR" >&2
    exit 1
fi

SESSION_NAME=$(basename "$1")

# Session
if ! tmux new-session -d -s "$SESSION_NAME" -A -c "$SESSION_DIR"; then
    echo "[error] failed to create new session" >&2
    exit 1
fi

if [[ -d "$SESSION_DIR/.devshells" ]]; then
    if command -v nix-develop &> /dev/null; then
        if ! tmux send-keys -t "$SESSION_NAME" "nix-develop" C-m; then
            echo "[error] failed to load dev env" >&2
            exit 1
        fi
    fi
fi

exit 0
